version: "3.8"

services:
  db:
    image: mariadb:11
    container_name: crm_mariadb
    restart: always
    environment:
      # Użyj silnego hasła i zmiennych środowiskowych w przyszłości
      MARIADB_ROOT_PASSWORD: kapljca
      MARIADB_DATABASE: crm_project
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - crm-network

  crm-api:
    build:
      context: ./backend
      dockerfile: CRM.API/Dockerfile
    container_name: crm_api_service
    restart: always
    ports:
      # Używamy portu 5000 dla spójności
      - "5001:5000"
    depends_on:
      - db
    environment:
      # Aplikacja wewnątrz Dockera łączy się z bazą 'db' po nazwie serwisu
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=crm_project;user=root;password=kapljca
      # Ustawienie portu, na którym nasłuchuje Kestrel wewnątrz kontenera
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - crm-network

  crm-ui:
    build:
      context: ./crm-ui
      dockerfile: Dockerfile
    container_name: crm_ui_service
    restart: always
    ports:
      # Aplikacja frontendowa dostępna na porcie 5173
      - "5173:80"
    depends_on:
      - crm-api
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  mariadb_data:
